# -*- coding: utf-8 -*-
"""Copy of TRF github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bi4YlHFvdxyd_BvedGQTgr9Ro9jbApB-
"""

!pip install mtrf

from mtrf.model import TRF
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import scipy.io as io
import zipfile

from google.colab import drive
drive.mount('/content/drive')

data_EEGslow = '/content/drive/MyDrive/EEG_preprocesado_sep/slow'
data_EEGfast = '/content/drive/MyDrive/EEG_preprocesado_sep/fast'
S_slow = '/content/drive/MyDrive/Matrices_TRF/matriz_binaria/slow'
S_fast = '/content/drive/MyDrive/Matrices_TRF/matriz_binaria/fast'
print(os.listdir(data_EEGslow))
print(os.listdir(data_EEGfast))
print(os.listdir(S_slow))
print(os.listdir(S_fast))

"""Las señales EEG fueron filtradas y normalizadas por canal mediante estandarización z-score antes del entrenamiento de los modelos TRF. Los datos preprocesados fueron almacenados en formato NumPy (.npy) para asegurar reproducibilidad y eficiencia computacional."""

import numpy as np
#define channels subjects audios speed
canales = np.array([
    2,3,4,6,7,9,11,12,13,14,15,16,18,19,20,21,22,24,25,26,27,28,
    30,31,33,34,36,38,40,41,42,44,45,46,48,49,50,51,52,53,54,
    56,57,58,59,60,65
])-1

sujetos = [
    "01","02","04","05","09","12","13","14","15","17","19","20","21",
    "22","26","28","29","32","34","35","36","37","38","41","44","46","47",
    "48","51","52","54","55","59","62","65","67","68","72","74","75","77",
    "78","79","81","84"
]

auds = [f"{i:02d}" for i in range(1,24)]

velocidades = ["slow", "fast"]
fs = 250
lambda_exp = 10.0 ** np.arange(-7, 8)

def preparar_par(S, EEG):
    """
    S: (features_lag, T)  -> nos quedamos solo con la señal base
    EEG: (T, canales)
    """

    # Take only the first row (base stimulus).
    S = S[0, :]          # (T,)
    S = S[:, np.newaxis]  # (T, 1)

    T = min(S.shape[0], EEG.shape[0])
    S = S[:T, :]
    EEG = EEG[:T, :]

    return S, EEG

#Function to split data into training and test sets
def split_train_test(stim_list, eeg_list, test_ratio=0.2, seed=42):
    n = len(stim_list)
    idx = np.arange(n)
    rng = np.random.default_rng(seed)
    rng.shuffle(idx)

    split = int((1 - test_ratio) * n)
    train_idx = idx[:split]
    test_idx  = idx[split:]

    stim_train = [stim_list[i] for i in train_idx]
    eeg_train  = [eeg_list[i] for i in train_idx]
    stim_test  = [stim_list[i] for i in test_idx]
    eeg_test   = [eeg_list[i] for i in test_idx]

    return stim_train, eeg_train, stim_test, eeg_test

stimuli = { "slow": {}, "fast": {} }
responses = { "slow": {}, "fast": {} }
#Split training and testing cases globally
for sujeto in sujetos:
  for vel in velocidades:

        stim_cases = []
        eeg_cases  = []

        for ut in auds:
            try:
                # Load stimulus
                if vel == "slow":
                    S = np.load(f"/content/drive/MyDrive/Matrices_TRF/matriz_binaria/slow/ut{ut}.npy")
                else:
                    S = np.load(f"/content/drive/MyDrive/Matrices_TRF/matriz_binaria/fast/ut{ut}_F.npy")

                #Load EEGs
                eeg = np.load(
                    f"/content/drive/MyDrive/EEG_preprocesado_sep/{vel}/bb{sujeto}_ut{ut}.npy"
                )[:, canales]

                #Match stimulus-EEG
                S, eeg = preparar_par(S, eeg)
                #print(S.shape, eeg.shape)
                stim_cases.append(S)
                eeg_cases.append(eeg)

            except FileNotFoundError:
                #Case does not exist
                continue

        if len(stim_cases) < 2:
            continue
        # Split TRAIN / TEST
        S_tr, EEG_tr, S_te, EEG_te = split_train_test(
            stim_cases, eeg_cases, test_ratio=0.2
        )
        # Split TRAIN / VAL
        S_tr, EEG_tr, S_val, EEG_val = split_train_test(
            S_tr, EEG_tr, test_ratio=0.2
        )

        stimuli[vel][sujeto]  = {"train": S_tr, "test": S_te, "val": S_val}
        responses[vel][sujeto] = {"train": EEG_tr, "test": EEG_te,"val": EEG_val}

from mtrf.model import TRF
from scipy.stats import pearsonr
import numpy as np
#Choose the best lambda / Cross-validation
def seleccionar_lambda(S_train, y_train,S_val, y_val,fs, tmin, tmax, lambdas):

    trf = TRF(direction=1)

    scores = []

    for lam in lambdas:
        #Train the model using this lambda_i
        model = trf.train(S_train, y_train, fs, tmin, tmax, lam)

        # Predict on the same data
        y_pred_list = trf.predict(S_val, model)

        y_true_all = []
        y_pred_all = []

        for yt, yp in zip(y_train, y_pred_list):
            yt = np.asarray(yt).ravel()
            yp = np.asarray(yp).ravel()
            T = min(len(yt), len(yp))
            if T < 2:
                continue
            y_true_all.append(yt[:T])
            y_pred_all.append(yp[:T])

        if len(y_true_all) == 0:
            scores.append(np.nan)
        else:
            y_true = np.concatenate(y_true_all)
            y_pred = np.concatenate(y_pred_all)
            r, _ = pearsonr(y_true, y_pred)
            scores.append(r)

    # best lambda
    idx_best = np.nanargmax(scores)
    best_lambda = lambdas[idx_best]

    return best_lambda, scores

"""Formalmente, para cada canal $c$, el modelo estima la función de respuesta temporal $w^c(\tau)$ resolviendo el siguiente problema de optimización:

\begin{equation}
\hat{w}^{\,c}(\tau)
=
\arg\min_{w}
\left\|
y_c(t)
-
\sum_{k}
\sum_{\tau}
S_k(t-\tau)\, w_{k,c}(\tau)
\right\|^2
+
\lambda \|w\|^2
\end{equation}

donde:
    - $y_c(t)$ es la señal EEG observada en el canal $c$.
    - $S_k(t)$ representa el predictor $k$ del estímulo (por ejemplo, vocales o consonantes).
    - $w_{k,c}(\tau)$ es la TRF asociada al predictor $k$, canal $c$ y desfase $\tau$.
    - $\lambda$ es el parámetro de regularización que controla el compromiso entre ajuste y complejidad del modelo.

TRF directa (modelo forward):

\begin{equation}
\hat{Y}(t,c)
=
\sum_{k=1}^{K}
\sum_{\tau=0}^{\tau_{\max}}
S_k(t-\tau)\, w_{k,c}(\tau)
\end{equation}

donde:
    - $S_k(t)$: matriz de estímulo (fonemas vocales y consonantes con desfases temporales).
    - $Y(t,c)$: señal EEG en el tiempo $t$ y canal $c$.
    - $w_{k,c}(\tau)$: función de respuesta temporal (TRF), que modela la contribución del predictor $k$ al canal $c$ con desfase $\tau$.
    - $K$: cantidad de muestras (en este caso, vocales y consonantes).
    - $\tau$: desfase temporal (lags), con $0 \le \tau \le \tau_{\max}$.
"""

best_lambdas = {}
lambdas = 10.0 ** np.arange(-7, 8)
for vel in velocidades:

    S_train_all = []
    y_train_all = []
    S_val_all = []
    y_val_all = []

    for sujeto in sujetos:

        if sujeto not in responses[vel]:
            continue

        # stimuli train
        S_train = stimuli[vel][sujeto]["train"]

        # EEG train
        y_train = responses[vel][sujeto]["train"]

        S_train_all.extend(S_train)
        y_train_all.extend(y_train)

        #stimuli val and EEG val
        S_val = stimuli[vel][sujeto]["val"]
        y_val= responses[vel][sujeto]["val"]


        S_val_all.extend(S_val)
        y_val_all.extend(y_val)

    best_lambda, scores = seleccionar_lambda(
        S_train_all,
        y_train_all,
        S_val_all,
        y_val_all,
        fs=250,
        tmin=0,
        tmax=0.6,
        lambdas=lambdas
    )

    best_lambdas[vel] = best_lambda

#print(best_lambda)
#print(scores)

from mtrf.model import TRF
from scipy.stats import pearsonr
import numpy as np
results = {}
trf = TRF(direction=1)
#Loop de entrenamiento + test
for vel in ["slow", "fast"]:
    for sujeto in stimuli[vel]:

        if sujeto not in results:
            results[sujeto] = {}

        S_train = stimuli[vel][sujeto]["train"]
        EEG_train = responses[vel][sujeto]["train"]

        # ensure training data is not empty
        if not S_train or not EEG_train:
            print(f"Skipping {sujeto} {vel}: No training data available after splits.")
            continue

        S_test = stimuli[vel][sujeto]["test"]
        EEG_test = responses[vel][sujeto]["test"]

        for ci, canal in enumerate(canales):
          if canal not in results[sujeto]:
              results[sujeto][canal] = {}

          y_train = [e[:, ci] for e in EEG_train]
          y_test  = [e[:, ci] for e in EEG_test]

              # Final Model Training
          model = trf.train(
                        S_train,        # stimulus
                        y_train,        # response
                        250,            # fs
                        0,              # tmin
                        0.6,            # tmax (ya está desfasado)
                        best_lambda    #lambda
                    )


              #prediction with test data
          y_pred_list = trf.predict(S_test, model)

          y_true_all = []
          y_pred_all = []

          for yt, yp in zip(y_test, y_pred_list):

                  yt = np.asarray(yt).ravel()
                  yp = np.asarray(yp).ravel()
                  T = min(len(yt), len(yp))

                  if T < 2:
                    continue

                  y_true_all.append(yt[:T])
                  y_pred_all.append(yp[:T])


          if len(y_true_all) == 0:
                    r_test = np.nan
          else:
                    y_true = np.concatenate(y_true_all)
                    y_pred = np.concatenate(y_pred_all)
                    r_test, _ = pearsonr(y_true, y_pred)
                    results[sujeto][canal][vel] = r_test

print(len(y_true), len(y_pred))
print("N sujetos en results:", len(results))
print(results )

import numpy as np

r_slow = []
r_fast = []

for sujeto in results:
    for canal in results[sujeto]:
        if "slow" in results[sujeto][canal] and "fast" in results[sujeto][canal]:
            rs = results[sujeto][canal]["slow"]
            rf = results[sujeto][canal]["fast"]
            if not (np.isnan(rs) or np.isnan(rf)):
                r_slow.append(rs)
                r_fast.append(rf)


r_slow = np.array(r_slow)
r_fast = np.array(r_fast)

print("N pares:", len(r_slow))

from scipy.stats import ttest_rel

t, p = ttest_rel(r_fast, r_slow, nan_policy="omit")

print("Paired t-test")
print("t:", t)
print("p-value:", p)

diff = r_fast - r_slow
print("Diferencia media (fast - slow):", np.mean(diff))

cohen_d = np.mean(diff) / np.std(diff, ddof=1)
print("Cohen's d:", cohen_d)

#diff = r_fast - r_slow

plt.figure(figsize=(6,4))
plt.hist(diff, bins=40, color="steelblue", alpha=0.8)
plt.axvline(0, color="k", linestyle="--")
plt.xlabel("r_fast − r_slow")
plt.ylabel("Frecuencia")
plt.title("Distribución de diferencias pareadas (Fast − Slow)")
plt.grid(alpha=0.3)
plt.show()

plt.figure(figsize=(6,5))

plt.boxplot([r_slow, r_fast],
            labels=["Slow", "Fast"],
            showfliers=False)

for i in range(len(r_slow)):
    plt.plot([1, 2], [r_slow[i], r_fast[i]],
             color="gray", alpha=0.2)

plt.ylabel("Correlación r (test)")
plt.title(f"TRF prediction performance\nWilcoxon p = {p:.3e}")
plt.grid(alpha=0.3)
plt.show()

diff_by_subject = {}
for sujeto in results:
    ds = []
    for canal in results[sujeto]:
        if "slow" in results[sujeto][canal] and "fast" in results[sujeto][canal]:
            ds.append(results[sujeto][canal]["fast"] -
                      results[sujeto][canal]["slow"])
    if len(ds) > 0:
        diff_by_subject[sujeto] = np.median(ds)

plt.hist(diff_by_subject.values(), bins=20)
plt.axvline(0, color="k", ls="--")
plt.title("Mediana por sujeto (Fast − Slow)")
plt.show()